# Generated by Django 5.1.6 on 2025-03-30 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionlist",
            name="chef",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
