# Generated by Django 5.1.6 on 2025-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0003_positionlist_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionlist",
            name="image",
        ),
    ]
