# Generated by Django 5.1.7 on 2025-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0004_remove_positionlist_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionlist",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
