# Generated by Django 5.1.7 on 2025-04-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant_app",
            "0006_aboutus_address_aboutus_email_aboutus_history_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="description",
            new_name="feedback",
        ),
    ]
