# Generated by Django 5.1.7 on 2025-04-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0007_rename_description_feedback_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booktable",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
